application/snaps/models.py
import datetime, hashlib
from application import db

class Snap(db.Model):
	
	id = db.Column(db.Integer, primary_key=True)

	name = db.Column(db.String(128))

	extension = db.Column(db.String(12))

	content = db.Column(db.Text())

	def content_hash(context):
		content = context.current_parameters['content']
		created_on = context.current_parameters['created_on']
		return hashlib.sha1(content + str(created_on)).hexdigest()

	hash_key = db.Column(db.String(40), unique=True, default=content_hash)

	created_on = db.Column(db.DateTime, default=datetime.datetime.utcnow, index=True)

	user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

	user = db.relationship('User', backref=db.backref('snaps', lazy='dynamic'))

	def __repr__(self):
		return '<Snap {!r}>'.format(self.id)

"""
	def __init__(self, user_id, name, content, extension):
		self.user_id = user_id
		self.name = name
		self.content = content
		self.extension = extension
		self.created_on = datetime.datetime.utcnow()
		self.hash_key = hashlib.sha1(self.content + str(self.created_on)).hexdigest()

"""
	

application/snaps/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField
from wtforms.widgets import TextArea

class SnapsForm(FlaskForm):

	name = StringField('name', validators=[validators.DataRequired()])

	extension = StringField('extension', validators=[validators.DataRequired()])

	content = StringField('content', widget=TextArea(), validators=[validators.DataRequired()])

	submit = SubmitField('submit', validators=[validators.DataRequired()])

application/snaps/views.py
from flask import Blueprint, render_template, redirect, url_for, current_app, flash
from flask_login import login_required, current_user
from forms import SnapsForm
from models import Snap
from application import db
from sqlalchemy import exc

snaps = Blueprint('snaps', __name__, template_folder='templates')

@snaps.route("/", methods=['GET'])
def listing():
	snaps = Snap.query.order_by(Snap.created_on.desc()).limit(20).all()
	return render_template('snaps/index.html', snaps=snaps)


@snaps.route("/add", methods=['GET', 'POST'])
@login_required
def add():
	
	form = SnapsForm()

	if form.validate_on_submit():
		user_id = current_user.id

		snap = Snap(user_id = user_id,
                    name = form.name.data,
                    content = form.content.data,
                    extension = form.extension.data)

		db.session.add(snap)

		try:
			db.session.commit()
		except exc.SQLAlchemyError:
			current_app.logger.exception("Could not save new Snap")
			flash("Something went wrong while saving your Snap")

	else:
		return render_template('snaps/add.html', form=form)

	return redirect(url_for('snaps.listing'))

application/snaps/templates/add.html
{% extends "layout.html" %}

{% block content %}
	<form action="{{ url_for('snap.add') }}" method="post">
		{ form.csrf_token}
		<div class="row">
			<div>
				{{ form.name.label() }}: {{ form.name }}
			</div>
			{% if form.name.errors %}
				<ul class="errors">
					{% for error in form.name.errors %}
						<li>{{ error }}</li>
					{% endfor %}
				</ul>
			{% endif %}
			<div>
				{{ form.extensions.label() }}: {{ form.extensions }}
			</div>
			{% if form.extensions.errors %}
				<ul class="errors">
					{% for error in form.extensions.errors %}
						<li>{{ error }}</li>
					{% endfor %}
				</ul>
			{% endif %}
			<div class="row">
				<div>
					{{ form.content.label() }}: {{ form.content }}
				</div>
				{% if form.content.errors %}
					<ul>
						{% for error in form.content.errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
		</div>
	</form>
{% endblock %}

application/snaps/templates/snaps/add.html
{% extends "layout.html" %}

{% block content %}
	<form action="{{ url_for('snaps.add') }}" method="post">
		{{ form.csrf_token }}
		<div class="row">
			<div>
				{{ form.name.label() }}: {{ form.name }}
			</div>
			{% if form.name.errors %}
				<ul class="errors">
					{% for error in form.name.errors %}
						<li>{{ error }}</li>
					{% endfor %}
				</ul>
			{% endif %}
			<div>
				{{ form.extension.label() }}: {{ form.extension }}
			</div>
			{% if form.extension.errors %}
				<ul class="errors">
					{% for error in form.extension.errors %}
						<li>{{ error }}</li>
					{% endfor %}
				</ul>
			{% endif %}
			<div class="row">
				<div>
					{{ form.content.label() }}: {{ form.content }}
				</div>
				{% if form.content.errors %}
					<ul>
						{% for error in form.content.errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
			<div>{{ form.submit }}</div>
		</div>
	</form>
{% endblock %}

application/snaps/templates/snaps/index.html
{% extends "layout.html" %}


{% block content %}
<div class="new-snap">
	<p><a href="{{url_for('snaps.add')}}">New Snap</a></p>
</div>

{% for snap in snaps %}
<div class="snap">
	<span class="author">{{snap.user.username}}</span>, published on <span class="date">{{snap.created_on}}</span>
	<pre><code>{{snap.content}}</code></pre>
</div>
{% endfor %}

{% endblock %}