application/users/models.py
import datetime
from application import db, flask_bcrypt
from sqlalchemy.ext.hybrid import hybrid_property

class User(db.Model):

	id = db.Column(db.Integer, primary_key=True)

	email = db.Column(db.String(255), unique=True)

	username = db.Column(db.String(40), unique=True)

	#password = db.Column(db.String(60))

	created_on = db.Column(db.DateTime, default=datetime.datetime.utcnow)

	# hashed password for the user
	_password = db.Column('password', db.String(60))

	@hybrid_property
	def password(self):
		#bcrypted password of given user
		return self._password

	@password.setter
	def password(self, password):
		self._password = flask_bcrypt.generate_password_hash(password)


	def __repr__(self):
		return '<User {!r}>'.format(self.username)

	def is_authenticated(self):
		return True

	def is_active(self):
		return True

	def is_anonymous(self):
		return False

	def get_id(self):
		return unicode(self.id)

application/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, validators, SubmitField

class LoginForm(FlaskForm):
	
	username = StringField('username', validators=[validators.DataRequired()])

	password = PasswordField('password', validators=[validators.DataRequired(), validators.Length(min=6)])

	submit =  SubmitField('submit', validators=[validators.DataRequired()])

application/users/views.py
from flask import Blueprint, flash, render_template, url_for, redirect, g
from flask_login import login_user, logout_user, current_user

from forms import LoginForm

from models import User
from application import flask_bcrypt

users = Blueprint('users', __name__, template_folder='templates')


@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		redirect(urls_for('snaps.listing'))

	form = LoginForm()

	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()

		if not user or not flask_bcrypt.check_password_hash(user.password, form.password.data):
			flash("No such user exists.")
			return render_template('users/login.html', form=form)

		login_user(user, remember=True)
		return redirect(url_for('snaps.listing'))

	return render_template('users/login.html', form=form)



@users.route("/logout", methods=["GET"])
def logout():
	logout_user()
	return redirect(url_for('snaps.listing'))

application/users/templates/users/login.html
{% extends "layout.html" %}

{% block content %}
	<form action="{{ url_for('users.login') }}" method='post'>
		{{ form.csrf_token }}
		<div>{{ form.username.label }}: {{ form.username }}</div>
		{% if form.username.errors %}
			<ul class="errors">
				{% for error in form.username.errors %}
					<li>{{error}}</li>
				{% endfor %}
			</ul>
		{% endif %}
		<div>{{ form.password.label }}: {{ form.password }} </div>
		{% if form.password.errors %}
			<ul class="errors">
				{% for error in form.password.errors %}
					<li>{{error}}</li>
				{% endfor %}
			</ul>
		{% endif %}
		<div>{{ form.submit }}</div>
	</form>
{% endblock %}